services:
    CalendarBundle\Serializer\Serializer:
        class: CalendarBundle\Serializer\Serializer

    CalendarBundle\Serializer\SerializerInterface:
        alias: CalendarBundle\Serializer\Serializer

    calendar.serializer:
        alias: CalendarBundle\Serializer\Serializer

    CalendarBundle\Request\RequestParser:
        class: CalendarBundle\Request\RequestParser

    CalendarBundle\Request\RequestParserInterface:
        alias: CalendarBundle\Request\RequestParser

    CalendarBundle\Controller\CalendarController:
        class: CalendarBundle\Controller\CalendarController
        public: true
        autowire: true
        arguments:
            $eventDispatcher: '@event_dispatcher'
            $serializer: '@CalendarBundle\Serializer\Serializer'
            $requestParser: '@CalendarBundle\Request\RequestParser'
        tags:
            - controller.service_arguments

    calendar.controller:
        alias: CalendarBundle\Controller\CalendarController
        public: true
